title = "Haichao Zhu"
baseURL = "hczhu.fun"
theme = "researcher"
disableKinds = []
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[taxonomies]
  tag = "tags"

[params]
  author = "Haichao Zhu"
  description = ""
  favicon = "favicon.png"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer]
    text = ""
    url = ""
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#2E86C1"
#   [[params.socialIcons]]
#     icon = "fas fa-envelope"
#     title = "E-mail"
#     url = "mailto:mail@example.com"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "CV"
    url = "/cv.pdf"
    # 'pre' and 'post' hooks are available
    # here we use an icon from Bootstrap https://icons.getbootstrap.com/
    # post = '<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-person-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M2 2a2 2 0 0 1 2-2h5.293A1 1 0 0 1 10 .293L13.707 4a1 1 0 0 1 .293.707V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2zm7.5 1.5v-2l3 3h-2a1 1 0 0 1-1-1zM11 8a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm2 5.755S12 12 8 12s-5 1.755-5 1.755V14a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-.245z"/></svg> '
    weight = 1
  [[menu.main]]
    name = "Mail"
    url = "mailto:hczhu@ir.hit.edu.cn"
    weight = 2
  [[menu.main]]
    name = "Google Scholar"
    url = "https://scholar.google.com/citations?user=A9zyRzIAAAAJ"
    weight = 3
  [[menu.main]]
    name = "Github"
    url = "https://github.com/haichao592"
    weight = 4
  [[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/haichao-zhu-8b41727a/"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
